name: Dart

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: "2.19.0-146.2.beta"

      - name: Install dependencies
        run: dart pub get
        working-directory: glados

      - name: Analyze project source
        run: dart analyze
        working-directory: glados

      - name: Get test files
        run: tests=$(find test -name "*_test.dart")
        shell: bash
        id: test_files
        working-directory: glados

      - name: Run tests
        run: dart pub run test ${{ steps.test_files.outputs.tests }}
        shell: bash
        working-directory: glados

      - name: Coverage information
        working-directory: glados
        run: |
          dart pub global activate coverage
          dart pub global run coverage:test_with_coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
        working-directory: glados
